services:

  mosquitto_one:
    image: ${MOSQUITTO_IMAGE}
    container_name: mosquitto_one
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - local

networks:
  local:
    name: ${NETWORK_NAME}